DROP TABLE IF EXISTS `#__seoboss_keywords`;
DROP TABLE IF EXISTS `#__seoboss_keywords_items`;
DROP TABLE IF EXISTS `#__seoboss_metadata`;
DROP TABLE IF EXISTS `#__seoboss_redirects`;
DROP TABLE IF EXISTS `#__seoboss_settings`;
DROP TABLE IF EXISTS `#__seoboss_client_features`;
DROP TABLE IF EXISTS `#__seoboss_files_to_delete`;
DROP TABLE IF EXISTS `#__seoboss_default_tags`;
DROP TABLE IF EXISTS `#__seoboss_ping_status`;
