DROP TABLE IF EXISTS `#__osmeta_keywords`;
DROP TABLE IF EXISTS `#__osmeta_keywords_items`;
DROP TABLE IF EXISTS `#__osmeta_metadata`;
DROP TABLE IF EXISTS `#__osmeta_redirects`;
DROP TABLE IF EXISTS `#__osmeta_settings`;
DROP TABLE IF EXISTS `#__osmeta_client_features`;
DROP TABLE IF EXISTS `#__osmeta_files_to_delete`;
DROP TABLE IF EXISTS `#__osmeta_default_tags`;
DROP TABLE IF EXISTS `#__osmeta_ping_status`;
